on: # yamllint disable-line rule:truthy
  push:
    branches: ["main", "preop"]

name: Create container image

jobs:
  test-model-file-access:
    runs-on: ubuntu-latest
    steps:
      - name: Test model file access
        run: |
          curl -v -o /dev/null \
            "https://lake.fmi.fi/ml-models/meps-ml-correction/meps_lsm.grib"

  call-image-build-workflow:
    needs: test-model-file-access
    uses: fmidev/github-actions-workflows/.github/workflows/imagebuild-workflow.yaml@main
    with:
      image_name: ecmwf_ml_correction
      image_test_command: python3 /ecmwf_ml_correction/xgb_predict.py --help
    secrets:
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
